---
 - name: Retrieve Router IP Address
   hosts: RouterA
   gather_facts: no
   connection: network_cli

   tasks:
     - name: Show IP Address
       ios_command:
         commands:
           - show ip interface brief
       register: ip_output

     - name: Display IP Address
       debug:
         var: ip_output.stdout_lines
